export const hotelNames=[{
    id:1,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh2SnNCm98BdXVCn71jbJXDB3nl46xrG992Q&usqp=CAU",
    name:"One Eighties",
    price:7500,
    address:"2699 Green Valley, Highland Lake",
    city:"Austin",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"apartments"
},
{
    id:6,
    image:"https://i.insider.com/57f3b01a57540cad028b4684?width=910&format=jpeg",
    name:"Seaview Apartments",
    price:5500,
    address:"2699 Green Valley, Highland Lake",
    city:"Austin",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"apartments"
},{
    id:2,
    image:"https://static.trip101.com/main_pics/286267/medium.jpg",
    name:"Solage",
    price:1000,
    address:"2699 Green Valley, Highland Lake",
    city:"Austin",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:7,
    image:"https://www.rentcafe.com/blog/wp-content/uploads/sites/62/2016/06/Inman-Quarter-Apartments-in-Atlanta-via-RentCafe.jpg",
    name:"Darling Building",
    price:400,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"apartments"
},{
    id:8,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP_Uq1NS-wrkq_OGXm0bqsxTFjkgD774_FBw&usqp=CAU",
    name:"Rockwell",
    price:700,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"apartments"
},{
    id:9,
    image:"https://www.cuddlynest.com/blog/wp-content/uploads/2020/08/cabin-in-tennessee.jpg",
    name:"Golden",
    price:2100,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"cabins"
},{
    id:10,
    image:"https://www.brides.com/thmb/10oXEjkEh-vTWNiaNhTbily1uz0=/500x350/filters:no_upscale():max_bytes(200000):strip_icc()/Magee_Cabin_Exterior_TZ_DanHam1-3704114c17bc45ae808052c609d56f98.jpg",
    name:"Whistling",
    price:4500,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"cabins"
},{
    id:11,
    image:"https://www.pigeonforge.com/wp-content/uploads/cabins-usa-6.jpg",
    name:"Coyote",
    price:3500,
    address:"2699 Green Valley, Highland Lake",
    city:"Austin",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"cabins"
},{
    id:12,
    image:"https://cdn.fodors.com/ee/files/slideshows/3-The-Lodge-Spa-at-Brush-Creek-Ranch.jpg",
    name:"Meadow",
    price:2000,
    address:"2699 Green Valley, Highland Lake",
    city:"Los Angeles",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"cabins"
},{
    id:13,
    image:"https://www.travelandleisure.com/thmb/aQ0JB3qQggqgnOAChFCPFXVqfO8=/1800x1012/smart/filters:no_upscale():focal(593x611:595x613)/us-resort-hotels-nobu-ryokan-malibu-00-USRESORTSWB21-dfd682c18e4046aaac31f50eacf3e3b2.jpg",
    name:"Acqualina",
    price:420,
    address:"2699 Green Valley, Highland Lake",
    city:"Boston",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
},{
    id:3,
    image:"https://imgcy.trivago.com/c_lfill,d_dummy.jpeg,e_sharpen:60,f_auto,h_360,q_auto,w_360/itemimages/89/90/899055_v3.jpeg",
    name:"Fairmont",
    price:1595,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:14,
    image:"https://www.planetware.com/wpimages/2020/09/united-states-best-all-inclusive-resorts-ocean-key-resort-spa.jpg",
    name:"Kapalua",
    price:400,
    address:"2699 Green Valley, Highland Lake",
    city:"Los Angeles",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
},{
    id:15,
    image:"https://i.insider.com/611bf7f6c040ad0018ceb74c?width=700",
    name:"Valencia",
    price:6500,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
},{
    id:16,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBmBheTCvkj2qypbjwoopvvDZY34HVOmp6dQ&usqp=CAU",
    name:"Encore ",
    price:1365,
    address:"2699 Green Valley, Highland Lake",
    city:"Nashville",
    numberOfBeds:2,
    numberOfBathrooms:2,
    area:"5*9",
    categories:"resorts"
},{
    id:17,
    image:"https://mybeautifuladventures.com/wp-content/uploads/2016/06/9601040197_4a25167135_b.jpg",
    name:"Wynn",
    price:4310,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:4,
    numberOfBathrooms:4,
    area:"5*4",
    categories:"resorts"
},{
    id:18,
    image:"https://res.cloudinary.com/simplotel/image/upload/x_0,y_168,w_768,h_432,r_0,c_crop,q_80,fl_progressive/w_400,f_auto,c_fit/symphony-resorts/Samudra_Image_xwlplw",
    name:"Inn & Club",
    price:3966,
    address:"2699 Green Valley, Highland Lake",
    city:"Nashville",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"6*7",
    categories:"resorts"
},{
    id:19,
    image:"https://lh3.googleusercontent.com/-8JPrttMCOsQxyqmkZ01c1EGbYGIW3eOzZGFUN1jb5PjDrSvi8jHezK2xYZZ8UBKo4ZwMDCXGbuhrGUYqBx6TexbsIKHxzkfRA_RbfU=s540",
    name:" Little Nell",
    price:4500,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
},{
    id:20,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPku8-CsfmOu08IWDfeL6-zCjstnsiUx0NI9E8tdjfqYBvSa5OxGE3C6wKZvA3xyK25yw&usqp=CAU",
    name:"Park Harbor",
    price:3100,
    address:"2699 Green Valley, Highland Lake",
    city:"Boston",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*1",
    categories:"hotels"
},{
    id:4,
    image:"https://media.istockphoto.com/photos/american-craftsman-house-picture-id178559422?k=20&m=178559422&s=612x612&w=0&h=EXdN4TKEqcnCfei4ynpbAT49hg8Nc--vvN6oEIThU_0=",
    name:"Twin Farm",
    price:2100,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"cabins"
},{
    id:21,
    image:"https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_14/1423364/the_surfjack-best_cheap_hotels_in_the_us-040519.jpg",
    name:"Peninsula ",
    price:5400,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"hotels"
},{
    id:22,
    image:"https://www.gannett-cdn.com/presto/2022/02/07/USAT/db2d5db7-515f-4799-ad7d-78f14ab33204-image7.jpg?crop=1998%2C1124%2Cx0%2Cy128&width=1200",
    name:"Emma",
    price:750,
    address:"2699 Green Valley, Highland Lake",
    city:"San Jose",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"hotels"
},{
    id:23,
    image:"https://moneyinc.com/wp-content/uploads/2018/02/Redbury.jpg",
    name:"RedBury Inn",
    price:1500,
    address:"2699 Green Valley, Highland Lake",
    city:"Chicago",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"hotels"
},{
    id:24,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFplAO6CwRcw-xClL1bB2dCheL4K2NP9bh8A&usqp=CAU",
    name:"Carlyle",
    price:2800,
    address:"2699 Green Valley, Highland Lake",
    city:"San Jose",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"hotels"
},{
    id:25,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqzO8obGBWXXDMhmE47XJLm9loL0-bgLRLDg&usqp=CAU",
    name:"Langham",
    price:1450,
    address:"2699 Green Valley, Highland Lake",
    city:"Boston",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"hotels"
},{
    id:26,
    image:"https://assets.traveltriangle.com/blog/wp-content/uploads/2018/08/Sheraton-Vistana-Resort-Villas-Lake-Buena-Vista.jpg",
    name:"Sheraton",
    price:3999,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:27,
    image:"https://media.villagetaways.com/villas/usa/3472/f03106167c6699fc5021aefb8601b15c_full.jpg",
    name:"Mauna Kea",
    price:4080,
    address:"2699 Green Valley, Highland Lake",
    city:"Boston",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:28,
    image:"https://images.squarespace-cdn.com/content/v1/5ce0d6fc4f7fd8000187ac7a/1605389175208-BXL7IML13UO6U3U54MC1/HVN+-+USA+-+FL+-+villa+-+Miami+Floating+villa.jpg?format=1000w",
    name:"The Villa",
    price:740,
    address:"2699 Green Valley, Highland Lake",
    city:"Chicago",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:29,
    image:"https://elitelyfe-prod.s3.us-east-2.amazonaws.com/storage/Promo/8qhFPsfN5V70i38Y.jpg",
    name:"Waterfront",
    price:1400,
    address:"2699 Green Valley, Highland Lake",
    city:"San Jose",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:30,
    image:"https://static1.mansionglobal.com/production/media/article-images/8244390e720d4099c4bfbebcc0e4c2b0/large_paradise-island-beach-house-villas-nassau-bahamas23.jpg",
    name:"Four Seasons",
    price:2200,
    address:"2699 Green Valley, Highland Lake",
    city:"Chicago",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
},{
    id:31,
    image:"https://static1.mansionglobal.com/production/media/article-images/8244390e720d4099c4bfbebcc0e4c2b0/large_paradise-island-beach-house-villas-nassau-bahamas23.jpg",
    name:"Vineyard",
    price:5300,
    address:"2699 Green Valley, Highland Lake",
    city:"Chicago",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"villas"
},{
    id:5,
    image:"https://cdn.architecturelab.net/wp-content/uploads/2018/08/country-river-cabins-467x350.jpg",
    name:"Newport",
    price:7500,
    address:"2699 Green Valley, Highland Lake",
    city:"New York",
    numberOfBeds:3,
    numberOfBathrooms:2,
    area:"5*7",
    categories:"resorts"
}


]